config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_scope :admin do
    get 'admins/sign_in', to: 'home#index' #failed sign ins will redirect to main page
    authenticated :admin do
      root 'order_items#index', as: :authenticated_admin_root
    end
  end
  
  devise_for :cashiers
  devise_scope :cashier do
    get 'customers/sign_in', to: 'home#index' #failed sign ins will redirect to main page
    authenticated :cashier do
      root 'cafesessions#index', as: :authenticated_cashier_root
    end
  end
  
  # wala nako gibutang ang mga resources sa devise scope because naa ra man sa controller ang before_authenticate
  
  resources :discount_codes
  
  resources :cashiers
  
  resources :services
  
  resources :order_items do
    collection do
      get 'undersupplied_products', to: 'order_items#undersupplied_products', as: 'undersupplied_products'
    end
  end
  
  resources :customers
  
  resources :cafesessions do
    collection do
      get ':id/customer_summary', to: 'cafesessions#customer_summary', as: 'customer_summary'
      get ':id/add_order', to: 'cafesessions#add_order', as: 'add_order'
      get ':id/add_service', to: 'cafesessions#add_service', as: 'add_service'
      get 'pending_orders', to: 'cafesessions#pending_orders', as: 'pending_orders'
      get 'change_status', to: 'cafesessions#change_status' #gets function and loads it
      get 'final_receipt', to: 'cafesessions#final_receipt'
    end
  end
  
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discount_code.rb
class DiscountCode < ApplicationRecord
    validates :discount_code, uniqueness: {message: "already exists.", case_sensitive: false}
    has_many :cafesessions
end

app/controllers/discount_codes_controller.rb
class DiscountCodesController < ApplicationController
  before_action :set_discount_code, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_admin!

  def index
    @discount_codes = DiscountCode.all
  end

  def new
    @discount_code = DiscountCode.new
  end
  
  def create
    @discount_code = DiscountCode.new(discount_code_params)
    
    if @discount_code.save
      redirect_to discount_codes_path, notice: "Discount code successfully added."
    else
      render :new
    end
  end

  def edit
    @discount_code = DiscountCode.find(params[:id])
  end

  def update
    @discount_code = DiscountCode.find(params[:id])
    if @discount_code.update_attributes(discount_code_params)
      redirect_to discount_codes_path, notice: "Discount code successfully updated."
    else
      render :edit
    end
  end

  private
    def set_discount_code
      @discount_code = DiscountCode.find_by(id: params[:id])
      redirect_to discount_codes_path, notice: "Discount codes not found." if @discount_code.nil?
    end
    
    def discount_code_params
      params.require(:discount_code).permit(:discount_code, :percentage, :code_status)
    end
end

app/helpers/discount_codes_helper.rb
module DiscountCodesHelper
end

app/views/discount_codes/_form.html.erb
<%= simple_form_for @discount_code do |f| %>
    <%= f.error_notification %>
    <%= f.input :id, label: "Discount Code", as: "string", required: true %>
    <%= f.input :percentage, collection: 1..99, prompt: "Percent off", selected: 21, required: true %>
    <%= f.input :code_status, as: :boolean %>
    <%= f.submit "Submit", class: "btn btn-outline-secondary" %>
    <%= link_to 'Back', discount_codes_path, class: "btn btn-primary" %>
<% end %>

app/views/discount_codes/edit.html.erb
<div class="container">
<div class="page-header">
    <h1 class="text-center";style="font-family:lato"> <strong> EDIT DISCOUNT CODE </strong> </h1>
</div>
<%= render 'form' %>

app/views/discount_codes/index.html.erb
<h1 class="text-center";style="font-family:lato"> DISCOUNT CODES </h1>
<br>
<br>
<%= link_to "Add Discount Code", new_discount_code_path, class: "btn btn-outline-secondary" %>
<br>
<br>
<table class="table table-striped">
    <thead>
        <th>Discount Code</th>
        <th>Percentage</th>
        <th>Status</th>
        <th>Option</th>
    </thead>
    <tbody>
        <% @discount_codes.each do |discount_code| %>
            <tr>
                <td>
                    <%= discount_code.id %>
                </td>
                <td>
                    <%= discount_code.percentage %>
                </td>
                <td>
                    <% if discount_code.code_status %>
                        <p class= "label label-success">Active</p>
                    <% else %>
                        <p class= "label label-danger">Inactive</p>
                    <% end %>
                </td>
                <td>
                    <% if discount_code.id.eql? 'NoDiscount' %>
                        <p>Uneditable</p>
                    <% else %>
                        <%= link_to "Edit", edit_discount_code_path(discount_code), class: "btn btn-primary" %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/discount_codes/new.html.erb
<div class="container">
    <h1 class="text-center";style="font-family:lato"> NEW DISCOUNT CODE </h1>
</div>

<%= render 'form' %>