config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_scope :admin do
    get 'admins/sign_in', to: 'home#index' #failed sign ins will redirect to main page
    authenticated :admin do
      root 'order_items#index', as: :authenticated_admin_root
    end
  end
  
  devise_for :cashiers
  devise_scope :cashier do
    get 'customers/sign_in', to: 'home#index' #failed sign ins will redirect to main page
    authenticated :cashier do
      root 'cafesessions#index', as: :authenticated_cashier_root
    end
  end
  
  # wala nako gibutang ang mga resources sa devise scope because naa ra man sa controller ang before_authenticate
  
  resources :discount_codes
  
  resources :cashiers
  
  resources :services
  
  resources :order_items do
    collection do
      get 'undersupplied_products', to: 'order_items#undersupplied_products', as: 'undersupplied_products'
    end
  end
  
  resources :customers
  
  resources :cafesessions do
    collection do
      get ':id/customer_summary', to: 'cafesessions#customer_summary', as: 'customer_summary'
      get ':id/add_order', to: 'cafesessions#add_order', as: 'add_order'
      get ':id/add_service', to: 'cafesessions#add_service', as: 'add_service'
      get 'pending_orders', to: 'cafesessions#pending_orders', as: 'pending_orders'
      get 'change_status', to: 'cafesessions#change_status' #gets function and loads it
      get 'final_receipt', to: 'cafesessions#final_receipt'
    end
  end
  
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :cafesessions
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_customer, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_cashier!
  
  def index
    @customers = Customer.order(sort_column + " " + sort_direction)
    # @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end
  
  def create
    @customer = Customer.new(customer_params)
    @customer.membership = false
    @customer.in_store = false
    
    if @customer.save
      redirect_to customers_path, notice: "Customer successfully added."
    else
      render :new
    end
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    if @customer.update_attributes(customer_params)
      redirect_to customers_path, notice: "Customer successfully updated."
    else
      render :edit
    end
  end

  # def destroy
  #   @customer = Customer.find(params[:id])
  #   @customer.destroy
  
  #   redirect_to customers_path
  # end
  
  private
    def set_customer
      @customer = Customer.find_by(id: params[:id])
      redirect_to customers_path, notice: "Customer not found." if @customer.nil?
    end
    
    def customer_params
      params.require(:customer).permit(:customer_name, :school_organization, :age, :mobile_number, :membership)
    end

    def sort_column
      Customer.column_names.include?(params[:sort]) ? params[:sort] : "customer_name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for @customer do |f| %>
    <%= f.error_notification %>
    <%= f.input :customer_name, as: "string", placeholder: "Full name", required: true %>
    <%= f.input :school_organization, label: "School/Organization", as: "string", placeholder: "School/Organization", required: true %>
    <%= f.input :age, as: :integer, input_html: { in: 10..99 }, prompt: "Age", required: true %>
    <%= f.input :mobile_number, as: "string", placeholder: "Mobile Number", required: true %>
    <%= f.submit "Submit", class: "btn btn-outline-secondary" %>
    <%= link_to 'Back', customers_path, class: "btn btn-primary" %>
<% end %>

app/views/customers/edit.html.erb
<div class="container">
<div class="page-header">
    <h1 class="text-center";style="font-family:lato"> <strong> EDIT CUSTOMER </strong> </h1>
</div>

<%= render 'form' %>

app/views/customers/index.html.erb
<h1 class="text-center";style="font-family:lato"> CUSTOMER DIRECTORY </h1>
<br>
<br>
<%= link_to "Register New Customer", new_customer_path, class: "btn btn-outline-secondary" %>
<br>
<table class="table table-striped">
<br>
    <thead>
        <th><%= sortable "name" %></th>
        <th><%= sortable "school_organization", "School/Organization" %></th>
        <th><%= sortable "age" %></th>
        <th>Mobile Number</th>
        <th><%= sortable "membership" %></th>
        <th>Options</th>
    </thead>
    <tbody>
        <% @customers.each do |customer| %>
            <tr>
                <td>
                    <%= customer.customer_name %>
                </td>
                <td>
                    <%= customer.school_organization %>
                </td>
                <td>
                    <%= customer.age %>
                </td>
                <td>
                    <%= customer.mobile_number %>
                </td>
                <td>
                    <% if customer.membership %>
                    <p> Yes</p>
                    <% else %>
                    <p> No</p>
                    <% end %>
                </td>
                <td>
                    <% if customer.in_store %>
                        <button type="button" class="btn btn-secondary btn-sm" disabled>Timed-in</button>
                    <% else %>
                        <%= link_to "Time In", cafesessions_path(:customer_id => customer), :method => :post, class: "btn btn-outline-success btn-sm" %>  
                    <% end %>
                    <%= link_to "Edit", edit_customer_path(customer), class: "btn btn-primary btn-sm" %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/customers/new.html.erb
<div class="container">
    <h1 class="text-center";style="font-family:lato"> CUSTOMER REGISTRATION </h1>
</div>

<%= render 'form' %>