config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_scope :admin do
    get 'admins/sign_in', to: 'home#index' #failed sign ins will redirect to main page
    authenticated :admin do
      root 'order_items#index', as: :authenticated_admin_root
    end
  end
  
  devise_for :cashiers
  devise_scope :cashier do
    get 'customers/sign_in', to: 'home#index' #failed sign ins will redirect to main page
    authenticated :cashier do
      root 'cafesessions#index', as: :authenticated_cashier_root
    end
  end
  
  # wala nako gibutang ang mga resources sa devise scope because naa ra man sa controller ang before_authenticate
  
  resources :discount_codes
  
  resources :cashiers
  
  resources :services
  
  resources :order_items do
    collection do
      get 'undersupplied_products', to: 'order_items#undersupplied_products', as: 'undersupplied_products'
    end
  end
  
  resources :customers
  
  resources :cafesessions do
    collection do
      get ':id/customer_summary', to: 'cafesessions#customer_summary', as: 'customer_summary'
      get ':id/add_order', to: 'cafesessions#add_order', as: 'add_order'
      get ':id/add_service', to: 'cafesessions#add_service', as: 'add_service'
      get 'pending_orders', to: 'cafesessions#pending_orders', as: 'pending_orders'
      get 'change_status', to: 'cafesessions#change_status' #gets function and loads it
      get 'final_receipt', to: 'cafesessions#final_receipt'
    end
  end
  
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cafesession.rb
class Cafesession < ApplicationRecord
    validates :table_number, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
    has_many :order_lines, inverse_of: :cafesession
    has_many :order_items, through: :order_lines
    has_many :service_lines, inverse_of: :cafesession
    has_many :services, through: :service_lines
    accepts_nested_attributes_for :order_lines, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :service_lines, reject_if: :all_blank, allow_destroy: true
    # accepts_nested_attributes_for :order_items
    belongs_to :cashier
    belongs_to :customer
    belongs_to :discount_code
end

app/controllers/cafesessions_controller.rb
class CafesessionsController < ApplicationController
  before_action :set_cafesession, only: [:edit, :show, :update, :destroy, :add_order, :add_service, :customer_summary, :final_receipt]
  before_action :authenticate_cashier!
  
  def index
    @cafesessions = Cafesession.where("finished = false").order('time_in')
  end

  def customer_summary
    start = @cafesession.time_in
    finish = DateTime.now
    
    # Saving the shit
    @cafesession.time_out = finish
    @cafesession.save
    
    duration = @cafesession.time_out.to_time - start.to_time

    hours = duration/60/60
    minutes = duration/60%60
    seconds = duration%60

    @duration_in_store = "#{hours.to_i}h #{minutes.to_i}min #{seconds.to_i}sec"

    # every hour 70, after 5 hours 350
    # 0:00:00-1:15:59, 70
    # 1:16:00-2:15:59, 140
    # 2:16:00-3:15:59, 210
    # 3:16:00-4:15:59, 280
    # 4:16:00-forever, 350

    # I wish to optimize this messy code lol
    first_hour = (1 * 3600 + 16 * 60)
    second_hour = (2 * 3600 + 16 * 60)
    third_hour = (3 * 3600 + 16 * 60)
    fourth_hour = (4 * 3600 + 16 * 60)

    fee = 0
    hour_bracket = 0

    if duration < first_hour
      fee = 70
      hour_bracket = 1
    elsif duration >= first_hour and duration < second_hour
      fee = 70 * 2
      hour_bracket = 2
    elsif duration >= second_hour and duration < third_hour
      fee = 70 * 3
      hour_bracket = 3
    elsif duration >= third_hour and duration < fourth_hour
      fee = 70 * 4
      hour_bracket = 4
    elsif duration >= fourth_hour
      fee = 70 * 5
      hour_bracket = 5
    end

    @stayfee = fee
    @hour_bracket = hour_bracket
  end

  def final_receipt
    @cafesession.finished = true
    @customer = @cafesession.customer
    @customer.in_store = false

    if @cafesession.save and @customer.save
      flash[:notice] = "Goodbye! #{@customer.customer_name}"
    else
      flash[:alert] = "Error"
    end
  end

  def create
    @customer = Customer.find_by_id(params[:customer_id])
    if @customer.in_store
      redirect_to customers_path, alert: "That customer is already timed in."
    else
      @cafesession = current_cashier.cafesessions.new(customer: @customer)
      @cafesession.time_in = DateTime.now
      @cafesession.time_out = DateTime.now
      @cafesession.subtotal = 0
      @cafesession.date = Date.today
      @cafesession.table_number = 0
      @cafesession.discount_code = DiscountCode.find('NoDiscount')
      @cafesession.card_number = nil
      @cafesession.discount_amount = 0
      @cafesession.total_amount = 0
      @cafesession.vat = 0
      @cafesession.cash = 0
      @cafesession.finished = false
  
      @customer.in_store = true
      
      if @cafesession.save and @customer.save
        redirect_to cafesessions_path, notice: "Customer Successfully Timed in."
      else
        redirect_to customers_path, alert: "Customer Couldn't be Timed in."
      end
    end
  end

  def update
    if params[:commit] == 'Update table number'
      if @cafesession.update(cafesession_params)
        redirect_to @cafesession, notice: "Table number updated."
      else
        redirect_to @cafesession, alert: "Invalid table number"
      end
    elsif params[:commit] == 'Save orders' || params[:commit] == 'Save services'
      if params[:commit] == 'Save orders'
        # checks if order is too much
        # @cafesession.order_lines.each do |order_line|
        #   order_too_much = order_line.order_quantity <
        # end

        if @cafesession.update(cafesession_params_add_order)
          redirect_to @cafesession, notice: "Order Successfully Sent."
        else
          redirect_to add_order_cafesession_path(@cafesession), alert: "Order Not Sent."
        end
      elsif params[:commit] == 'Save services'
        if @cafesession.update(cafesession_params_add_service)
          redirect_to @cafesession, notice: "Service Successfully Added."
        else
          redirect_to add_service_cafesession_path(@cafesession), alert: "Service Not Added."
        end
      end
    end
    if params[:commit] == 'Proceed to Final Receipt'
      if @cafesession.update(cafesession_params)
        # redirect_to final_receipt_cafesessions_path(@cafesession)"
      else
        flash[:alert] = "Error"
      end
    end
  end

  def change_status #changes the status of the ORDER
    @order_line = OrderLine.find_by(id: params[:id])
    @order_item = @order_line.order_item

    if @order_line.order_status == false
      @order_line.order_status = true
      temp = @order_item.item_product_level
      @order_item.item_product_level -= @order_line.order_quantity

      if @order_line.save and @order_item.save
        redirect_to pending_orders_cafesessions_path, notice: "Order served.\nProduct level of #{@order_line.order_item.item_name}: #{temp} - #{@order_line.order_quantity} = #{@order_item.item_product_level}"
      else
        redirect_to pending_orders_cafesessions_path, alert: "Error."
      end
    else
      redirect_to pending_orders_cafesessions_path, alert: "Error."
    end
  end

  private
    def set_cafesession
      @cafesession = Cafesession.find_by(id: params[:id])
      redirect_to cafesessions_path, alert: "Cafe Session Not Found." if @cafesession.nil?
    end
    
    def cafesession_params_add_order
      params.require(:cafesession).permit(order_lines_attributes: [:order_item_id, :cafesession_id, :order_status, :order_quantity, :_destroy])
      # OrderLine.attribute_names.map(&:to_sym).push(:_destroy)
    end

    def cafesession_params_add_service
      params.require(:cafesession).permit(service_lines_attributes: [:service_id, :cafesession_id, :service_quantity, :_destroy])
      # ServiceLine.attribute_names.map(&:to_sym).push(:_destroy)
    end

    def cafesession_params
      params.require(:cafesession).permit!
    end
end

app/helpers/cafesessions_helper.rb
module CafesessionsHelper
end

app/views/cafesessions/_order_line_fields.html.erb
<div class='nested-fields order-line-fields'>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Product name</h3>
    </div>
    <div class="panel-body">
      <%= f.collection_select :order_item_id, OrderItem.where(item_status: true), :id, :item_name, required: true %>
      <%= f.input :order_quantity, as: "integer", placeholder: "Quantity", input_html: { min: '0', step: '1' }, required: true %>
      <%= f.hidden_field :order_status, :value => false %>
      
      <%= link_to_remove_association "Remove item", f, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"%>
    </div>
  </div>
</div>

app/views/cafesessions/_service_line_fields.html.erb
<div class='nested-fields service-line-fields'>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Service Name</h3>
    </div>
    <div class="panel-body">
      <%= f.collection_select :service_id, Service.where(service_status: true), :id, :service_name, required: true %>
      <%= f.input :service_quantity, as: "integer", placeholder: "Quantity", input_html: { min: '0', step: '1' }, required: true %>

      <%= link_to_remove_association "Remove service", f, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"%>
    </div>
  </div>
</div>

app/views/cafesessions/add_order.html.erb
<h1>Table Number <%= @cafesession.table_number %>: <%= @cafesession.customer.customer_name %></h1>
What do you want to order?

<%= simple_form_for @cafesession do |f| %>
    <%= f.error_notification %>
    <div id="order_lines">
        <%= f.simple_fields_for :order_lines do |order_line| %>
            <%= render 'order_line_fields', f: order_line %>
        <% end %>
        <div class="links">
            <%= link_to_add_association 'Add item', f, :order_lines, class: "btn btn-primary" %><br>
        </div>
    </div>
    <%= f.submit 'Save orders', class: "btn btn-primary" %>
    <%= link_to "Cancel", @cafesession, class: "btn btn-primary" %>
<% end %>
<br>

app/views/cafesessions/add_service.html.erb
<h1>Table Number <%= @cafesession.table_number %>: <%= @cafesession.customer.customer_name %></h1>
What service do you want to add?

<%= simple_form_for @cafesession do |f| %>
    <%= f.error_notification %>
    <div id="service_lines">
        <%= f.simple_fields_for :service_lines do |service_line| %>
            <%= render 'service_line_fields', f: service_line %>
        <% end %>
        <div class="links">
            <%= link_to_add_association 'Add Service', f, :service_lines, class: "btn btn-primary" %><br>
        </div>
    </div>
    <%= f.submit 'Save services', class: "btn btn-primary" %>
    <%= link_to "Cancel", @cafesession, class: "btn btn-primary" %>
<% end %>
<br>

app/views/cafesessions/customer_summary.html.erb
	<div class="page-header">
		<h1 class="text-center">Customer Summary</h1>
	</div>


<div>
<h1>Table Number: <%= @cafesession.table_number %></h1>
<h4>Cashier: <%= @cafesession.cashier.name %></h4>
<h4>Time In: <%= @cafesession.time_in.strftime("%H:%M:%S %A, %b %d, %Y") %></h4>
<h4>Time Out: <%= @cafesession.time_out.strftime("%H:%M:%S %A, %b %d, %Y") %></h4>
<h4>Duration: <%= @duration_in_store %></h4>
</div>

<% subtotal = 0 %>
<% subtotal2 = 0 %>

<table class="table table-striped">
    <thead>
        <th>Order Items</th>
        <th>Price per item</th>
        <th>Quantity</th>
        <th>Status</th>
        <th class="text-right">Price</th>
    </thead>
    <tbody>
        <% @cafesession.order_lines.each do |order_line| %>
            <tr>
                <td>
                    <%= order_line.order_item.item_name %>
                </td>
                <td>
                    <%= number_to_currency(order_line.order_item.item_price, unit: "₱") %>
                </td>
                <td>
                    <%= order_line.order_quantity %>
                </td>
                <td>
                    <% if order_line.order_status %>
                    <p class= "label label-success">Served</p>
                    <% else %>
                    <p class= "label label-warning">Pending</p>
                    <% end %>
                </td>
                <td class="text-right">
                    <% row_price = 0 %>
                    <% if order_line.order_status %>
                        <% row_price = order_line.order_quantity * order_line.order_item.item_price %>
                    <% else %>
                        <% row_price = 0 %>
                    <% end %>
                    <%= number_to_currency(row_price, unit: "₱") %>
                </td>
            </tr>
            <% subtotal += row_price %>
        <% end %>
        <tr>
            <td><b>Subtotal</b></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="text-right"><b><%= number_to_currency(subtotal, unit: "₱") %></b></td>
        </tr>
    </tbody>
</table>

<table class="table table-striped">
    <thead>
        <th>Services</th>
        <th>Quantity</th>
        <th class="text-right">Price</th>
    </thead>
    <tbody>
        <% @cafesession.service_lines.each do |service_line| %>
            <tr>
                <td>
                    <%= service_line.service.service_name %>
                </td>
                <td>
                    <%= service_line.service_quantity %>
                </td>
                <td class="text-right">
                    <%= number_to_currency(service_line.service_quantity * order_line.service.service_price, unit: "₱") %>
                </td>
            </tr>
            <% subtotal2 += service_line.service_quantity * service_line.service.service_price %>
        <% end %>
        <tr>
            <td>Subtotal</td>
            <td></td>
            <td class="text-right"><%= number_to_currency(subtotal2, unit: "₱") %></td>
        </tr>
    </tbody>
</table>


	<table class= "table">
        <% grandtotal = 0 %>
		<tr>
            <th>Orders Total</th>
            <th class="text-right"><%= number_to_currency(subtotal, unit: "₱") %></th>
        </tr>
		<tr>
            <th>Services Total</th>
            <th class="text-right"><%= number_to_currency(subtotal2, unit: "₱") %></th>
        </tr>
        <tr>
            <th>Stay Fees</th>
            <th class="text-right"><%= number_to_currency(70, unit: "₱") %>/hour × <%= @hour_bracket%> hour(s) = <%= number_to_currency(@stayfee, unit: "₱") %></th>
        </tr>
        <% grandtotal = subtotal + subtotal2 + @stayfee %>
	</table>



	<table class= "table">
		<tr>
            <td><b>Grand Total</b></td>
            <td class="text-right">
                <%= number_to_currency(grandtotal, unit: "₱") %>
            </td>
        </tr>
    </table>


<% @cafesession.subtotal = grandtotal %>
<% @cafesession.save %>

<div>
		<br>
        <%= simple_form_for @cafesession do |f| %>
            <%= f.input :cash, as: :integer, :min => grandtotal, required: true %>
            <%= f.association :discount_code, collection: DiscountCode.where(:code_status => true), :label_method => :id, :selected => 'NoDiscount', required: true %>
            <%= f.input :card_number, required: false %>
            <%= f.submit 'Proceed to Final Receipt', class: "btn btn-primary" %>
        <% end %>
        <table class= "table">
        
		<!--<tr>
            <th>Total</th>
            <%# <th class="text-right"><%= number_to_currency(grandtotal, unit: "₱") %></th> %>
        </tr>
		<tr>
            <th>Paid</th>
            <%# <th class="text-right"><%= number_to_currency(100, unit: "₱") %></th> %>
        </tr>
        <tr>
            <th>Change</th>
            <%# <th class="text-right"><%= number_to_currency(100-grandtotal, unit: "₱") %></th> %>
        </tr>-->
        
	</table>
</div>

app/views/cafesessions/final_receipt.html.erb
<div class="container">
	<div class="page-header">
		<h1 class="text-center">Customer Summary</h1>
	</div>
</div>

<div>
<h1>Table Number: <%= @cafesession.table_number %></h1>
<h2>Cashier: <%= @cafesession.Cashier.name %></h2>
<h3>Time Out: <h/3>
<h4>Date: <%= @cafesession.created_at %></h4>
</div>

<div class="container">
	<table class= "table">
        <tr><th>Order Items</th></tr>
		<tr>
            <th>Order Item</th>
            <th>Quantity</th>
            <th>Price</th>
        </tr>
		<% subtotal=0 %>
		
        <% @order_lines.each do |order_line| %>
		<tr>	
            <td><%= order_line.order_item.item_name %> </td>
            <td><%= order_line.order_quantity %></td>
            <td>₱<%= order_line.order_quantity * order_line.order_item.item_price %></td>
            <td><% subtotal += order_line.order_quantity * order_line.order_item.item_price %></td>
        </tr>
	    <% end %> 
        <tr>
            <th> Subtotal: ₱<%= subtotal %> </th>
        </tr>
	</table>
</div>
<br>

<div class="container">
	<table class= "table">
        <tr><th>Services</th></tr>
		<tr>
            <th>Service Name</th>
            <th>Quantity</th>
            <th>Price</th>
        </tr>
		<% subtotal2 =0 %>
		
        <% @service_lines.each do |service_line| %>
		<tr>	
            <td><%= service_line.service.service_name %> </td>
            <td><%= service_line.service_quantity %></td>
            <td>₱<%= service_line.service_quantity * service_line.service.service_price %></td>
            <td><% subtotal2 += service_line.service_quantity * service_line.service.service_price %></td>
        </tr>
	    <% end %> 
        <tr>
            <th> Subtotal: ₱<%= subtotal2 %> </th>
        </tr>
	</table>
</div>

<div class="container">
	<table class= "table">
        <% grandtotal = 0 %>
		<tr>
            <th>Orders Total</th>
            <th>₱<%= subtotal %></th>
        </tr>
		<tr>
            <th>Services Total</th>
            <th>₱<%= subtotal2 %></th>
        </tr>
        <tr>
            <th>Stay Fees</th>
            <th>Idk how to get the stay fee</th>
        </tr>
        <% grandtotal = subtotal + subtotal2 + stayfee $>
	</table>
</div>

<div class="container">
	<table class= "table">
		<tr>
            <th><b>Grand Total</b></th>
            <th>₱<%= grandtotal %></th>
        </tr>
    </table>
</div>

<div>
		<br>
        <h1>Discounted Total: ₱</h1>
        <h2>Paid: ₱<%= @cafesession.cash %> 
        <h2>Change: ₱<%= @cafesession.cash - discountedtotal%> </h2>
        
        
</div>

app/views/cafesessions/index.html.erb
<h1 class="text-center";style="font-family:lato"> CURRENT CUSTOMERS</h1>
<br>
<br>
<table class="table table-striped">
    <thead>
        <th>Name</th>
        <th>Time In</th>
        <th>Table Number</th>
        <th>Pending Orders</th>
        <th>Total Orders</th>
        <th>Options</th>
    </thead>
    <tbody>
        <% @cafesessions.each do |cafesession| %>
            <tr>
                <td>
                    <%= cafesession.customer.customer_name %>
                </td>
                <td>
                    <%= cafesession.time_in.strftime("%H:%M:%S %A, %b %d, %Y") %>
                </td>
                <td>
                    <%= cafesession.table_number %>
                </td>
                <td>
                    <%= OrderLine.where("cafesession_id = ?", cafesession.id).where("order_status = false").count%>
                </td>
                <td>
                    <%= OrderLine.where("cafesession_id = ?", cafesession.id).count%>
                </td>                
                <td>
                    <%= link_to "View", cafesession, class: "btn btn-primary" %> <!-- I think we should change this to Add order/service-->
                    <%= link_to "Time Out", customer_summary_cafesessions_path(cafesession), class: "btn btn-outline-danger" %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/cafesessions/pending_orders.html.erb
<!--don't show tables with emptiness
    if condition = nil -->

<div class="container">
	<div class="page-header">
	    <br>
		<h1 class="text-center">Pending Orders</h1>
	</div>
</div>
<div class="container">
    <% if Cafesession.where("finished = false").exists? %>
    <% i = 1 %>
    <% while i <= Cafesession.maximum("table_number") do %>
    <% @order_lines = OrderLine.joins(:cafesession).where("table_number = ?", i).where(:order_status => false) %>
        <% if @order_lines.exists? %>
            <h3>Table Number: <%= i %></h3>

            <table class="table">
                <th>Order Item</th>
                <th>Quantity ordered</th>
                <th>Quantity left</th>
                <th>Options</th>
                <% @order_lines.each do |order_line| %>
                <tr>
                    <td><%= order_line.order_item.item_name %> </td>
                    <td><%= order_line.order_quantity %></td>
                    <td><%= order_line.order_item.item_product_level %></td>
                    <td><%= link_to 'Serve', change_status_cafesessions_path(:id => order_line), class: 'btn btn-primary' %></td>
                </tr>
                <% end %>
            </table> 
        <% end %>
    <% i +=1 %>
    <% end %>
    <% else %>
        <h3 class="text-center">No customers in store</h3>
    <% end %>
    <!--<h3>Highest table: <%= Cafesession.maximum("table_number")%></h3>-->
</div>

app/views/cafesessions/show.html.erb
<h1 class="text-center">Table <b><%= @cafesession.table_number %></b>: <%= @cafesession.customer.customer_name %></h1>
<br>
<h4>Update Table Number</h4>
<%= simple_form_for @cafesession do |f| %>
    <%= f.error_notification %>
    <%= f.input :table_number, as: :integer, input_html: { in: 0..100 }, required: true %>
    <%= f.submit 'Update table number', class: "btn btn-primary" %>
<% end %>
<br>

<% if @cafesession.table_number != 0 %>
  <table class="table table-striped">
    <thead>
        <th>Product</th>
        <th>Status</th>
    </thead>
    <tbody>
        <% @cafesession.order_lines.each do |order_line| %>
            <tr>
                <td>
                    <%= order_line.order_item.item_name %>
                </td>
                <td>
                    <% if order_line.order_status %>
                    <p class= "label label-success">Served</p>
                    <% else %>
                    <p class= "label label-warning">Pending</p>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= link_to "Add Order", add_order_cafesessions_path(@cafesession), class: "btn btn-primary" %>
<br>
<br>
<table class="table table-striped">
    <thead>
        <th>Service</th>
    </thead>
    <tbody>
        <% @cafesession.service_lines.each do |service_line| %>
            <tr>
                <td>
                    <%= service_line.service.service_name %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= link_to "Add Service", add_service_cafesessions_path(@cafesession), class: "btn btn-primary" %>
<% else %>
<h3 class="text-center">Please set table number before adding orders and services.</h3>
<% end %>