config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_scope :admin do
    get 'admins/sign_in', to: 'home#index' #failed sign ins will redirect to main page
    authenticated :admin do
      root 'order_items#index', as: :authenticated_admin_root
    end
  end
  
  devise_for :cashiers
  devise_scope :cashier do
    get 'customers/sign_in', to: 'home#index' #failed sign ins will redirect to main page
    authenticated :cashier do
      root 'cafesessions#index', as: :authenticated_cashier_root
    end
  end
  
  # wala nako gibutang ang mga resources sa devise scope because naa ra man sa controller ang before_authenticate
  
  resources :discount_codes
  
  resources :cashiers
  
  resources :services
  
  resources :order_items do
    collection do
      get 'undersupplied_products', to: 'order_items#undersupplied_products', as: 'undersupplied_products'
    end
  end
  
  resources :customers
  
  resources :cafesessions do
    collection do
      get ':id/customer_summary', to: 'cafesessions#customer_summary', as: 'customer_summary'
      get ':id/add_order', to: 'cafesessions#add_order', as: 'add_order'
      get ':id/add_service', to: 'cafesessions#add_service', as: 'add_service'
      get 'pending_orders', to: 'cafesessions#pending_orders', as: 'pending_orders'
      get 'change_status', to: 'cafesessions#change_status' #gets function and loads it
      get 'final_receipt', to: 'cafesessions#final_receipt'
    end
  end
  
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
        :rememberable, :trackable, :validatable

  has_many :cashiers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cafesession.rb
class Cafesession < ApplicationRecord
    validates :table_number, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
    has_many :order_lines, inverse_of: :cafesession
    has_many :order_items, through: :order_lines
    has_many :service_lines, inverse_of: :cafesession
    has_many :services, through: :service_lines
    accepts_nested_attributes_for :order_lines, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :service_lines, reject_if: :all_blank, allow_destroy: true
    # accepts_nested_attributes_for :order_items
    belongs_to :cashier
    belongs_to :customer
    belongs_to :discount_code
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :rememberable, :trackable, :validatable

  belongs_to :admin
  has_many :cafesessions
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :cafesessions
end

app/models/discount_code.rb
class DiscountCode < ApplicationRecord
    validates :discount_code, uniqueness: {message: "already exists.", case_sensitive: false}
    has_many :cafesessions
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    validates :item_name, uniqueness: {message: "already exists.", case_sensitive: false}
    has_many :order_lines, inverse_of: :order_item
    has_many :cafesessions, through: :order_lines
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
    belongs_to :cafesession
    belongs_to :order_item
    # accepts_nested_attributes_for :order_item
end

app/models/service.rb
class Service < ApplicationRecord
    validates :service_name, uniqueness: {message: "already exists.", case_sensitive: false}
    has_many :service_lines, inverse_of: :service
    has_many :cafesessions, :through => :service_lines
end

app/models/service_line.rb
class ServiceLine < ApplicationRecord
    belongs_to :cafesession
    belongs_to :service
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_cashier, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_admin!
  
  def index
    @cashiers = Cashier.order(sort_column + " " + sort_direction)
  end

  def new
    @cashier = current_admin.cashiers.build
  end
  
  def create
   @cashier = current_admin.cashiers.new(cashier_params)
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully added."
    else
      render :new
    end
  end
  
  def edit
    @cashier = Cashier.find(params[:id])
  end

  def update
    @cashier = Cashier.find(params[:id])
    if @cashier.update_attributes(cashier_params)
      redirect_to cashiers_path, notice: "Cashier successfully updated."
    else
      render :edit
    end
  end

  def show
  end
 
  # def destroy #not using kay wala may status
  #   @cashier = Cashier.find(params[:id])
  #   if @cashier.status == true
  #     @cashier.status = false
  #   else
  #     @cashier.status = true
  #   end
    
  #   if @cashier.save
  #     redirect_to cashiers_path, notice: "Cashier successfully updated."
  #   end
  # end
  
  #version below turns change status to "delete cashier"
  # def destroy
  #   @cashier = Cashier.find(params[:id])
  #   @cashier.destroy
    
  #   redirect_to cashiers_path
  # end
  # def update # unya na ni
  #   @cashier = Cashier.find(params[:id])
  #   @cashier.destroy
  #   @cashier = current_admin.cashiers.new(cashier_params)
  #   if @cashier.save
  #     redirect_to cashiers_path, notice: "Cashier successfully updated."
  #   else
  #     render :edit
  #   end
  # end
  
  private
    def set_cashier
      @cashier = Cashier.find_by(id: params[:id])
      redirect_to cashiers_path, notice: "Cashier not found." if @cashier.nil?
    end
    
    def cashier_params
       params.require(:cashier).permit(:email, :password, :password_confirmation, :name, :address, :mobile_number, :date_hired) #-> Tried this
    end
    
    def sort_column
      Cashier.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        css_class = column == sort_column ? "current #{sort_direction}" : nil
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, {:sort => column, :direction => direction}, {:class => css_class}
    end
end

app/helpers/cafesessions_helper.rb
module CafesessionsHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/discount_codes_helper.rb
module DiscountCodesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diligence Cafe</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
   <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="color:white;">
      <div class="container">
        <div class="navbar-header">
        <a class="navbar-brand pull-left" href="#"> Diligence Café </a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if admin_signed_in? %>
              <li>
                <%= link_to "Order Items", order_items_path %>
              </li>
              <li>
                <%= link_to "Cashiers", cashiers_path %>
              </li>
              <li>
                <%= link_to "Discount Codes", discount_codes_path %>
              </li>
              <!-- Link to Reports coming soon-->
            <% end %>
            <% if cashier_signed_in? %>
              <li>
                <%= link_to "Dashboard", cafesessions_path %>
              </li>
              <li>
                <%= link_to "Customer Directory", customers_path %>
              </li>
              <li>
                <%= link_to "Pending Orders", pending_orders_cafesessions_path %>
              </li>
            <% end %>
            <% if cashier_signed_in? or admin_signed_in? %>
            <li>
                <%= link_to "Product Levels", undersupplied_products_order_items_path %>
            </li>
            <% end %>
          </ul>
          
          <p class="navbar-text pull-right">
          <% if admin_signed_in? %>
             Admin logged in as <strong> <%= current_admin.email %></strong> | 
            <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
          <% if cashier_signed_in? %>
            Cashier logged in as <strong><%= current_cashier.email %></strong> |
            <%= link_to "Logout", destroy_cashier_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
          </p>
        </div>
      </div>
    </nav>
    
    
    <div class="container">

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      
      <%= yield %>
    </div>
    
  </body>
</html>